// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core.dart';
import 'api/rdp.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCoreInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -878831189;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'termethis_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCoreInitApp();

  Future<bool> crateApiCorePrivateKeyIsEncrypted({required String pem});

  Future<void> crateApiRdpRdpClose({required PlatformInt64 sessionId});

  Future<RustRdpConnectResult> crateApiRdpRdpConnect({
    required RustRdpConnectRequest request,
  });

  Future<void> crateApiRdpRdpMouse({
    required PlatformInt64 sessionId,
    required int x,
    required int y,
    required int button,
    required bool pressed,
  });

  Future<RustRdpFrame> crateApiRdpRdpReadFrame({
    required PlatformInt64 sessionId,
    required PlatformInt64 afterSequence,
    required int waitMillis,
  });

  Future<RustRdpStatus> crateApiRdpRdpReadStatus({
    required PlatformInt64 sessionId,
  });

  Future<void> crateApiRdpRdpResize({
    required PlatformInt64 sessionId,
    required int width,
    required int height,
  });

  Future<void> crateApiRdpRdpSendScancode({
    required PlatformInt64 sessionId,
    required int scancode,
    required bool pressed,
  });

  Future<void> crateApiRdpRdpSendText({
    required PlatformInt64 sessionId,
    required String text,
  });

  Future<void> crateApiCoreSftpChangeDirectory({
    required PlatformInt64 sessionId,
    required String path,
  });

  Future<void> crateApiCoreSftpClose({required PlatformInt64 sessionId});

  Future<RustSftpConnectResult> crateApiCoreSftpConnect({
    required RustSftpConnectRequest request,
  });

  Future<void> crateApiCoreSftpCreateDirectory({
    required PlatformInt64 sessionId,
    required String name,
  });

  Future<String> crateApiCoreSftpCurrentDirectory({
    required PlatformInt64 sessionId,
  });

  Future<void> crateApiCoreSftpDeleteEmptyDirectory({
    required PlatformInt64 sessionId,
    required String name,
  });

  Future<void> crateApiCoreSftpDeleteFile({
    required PlatformInt64 sessionId,
    required String name,
  });

  Future<List<RustSftpEntry>> crateApiCoreSftpListDirectory({
    required PlatformInt64 sessionId,
  });

  Future<void> crateApiCoreSftpRename({
    required PlatformInt64 sessionId,
    required String oldName,
    required String newName,
  });

  Future<void> crateApiCoreSshClose({required PlatformInt64 sessionId});

  Future<RustSshConnectResult> crateApiCoreSshConnect({
    required RustSshConnectRequest request,
  });

  Future<RustSshConnectResult> crateApiCoreSshContinueAuthentication({
    required PlatformInt64 pendingAuthId,
    required List<String> responses,
  });

  Future<RustSshReadResult> crateApiCoreSshRead({
    required PlatformInt64 sessionId,
    required int maxBytes,
    required int waitMillis,
  });

  Future<void> crateApiCoreSshResize({
    required PlatformInt64 sessionId,
    required int width,
    required int height,
    required int pixelWidth,
    required int pixelHeight,
  });

  Future<void> crateApiCoreSshWrite({
    required PlatformInt64 sessionId,
    required List<int> data,
  });

  Future<void> crateApiCoreValidatePrivateKey({
    required String pem,
    String? passphrase,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCoreInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiCorePrivateKeyIsEncrypted({required String pem}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pem, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCorePrivateKeyIsEncryptedConstMeta,
        argValues: [pem],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePrivateKeyIsEncryptedConstMeta =>
      const TaskConstMeta(
        debugName: "private_key_is_encrypted",
        argNames: ["pem"],
      );

  @override
  Future<void> crateApiRdpRdpClose({required PlatformInt64 sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpRdpCloseConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpCloseConstMeta =>
      const TaskConstMeta(debugName: "rdp_close", argNames: ["sessionId"]);

  @override
  Future<RustRdpConnectResult> crateApiRdpRdpConnect({
    required RustRdpConnectRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_rust_rdp_connect_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_rdp_connect_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpRdpConnectConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpConnectConstMeta =>
      const TaskConstMeta(debugName: "rdp_connect", argNames: ["request"]);

  @override
  Future<void> crateApiRdpRdpMouse({
    required PlatformInt64 sessionId,
    required int x,
    required int y,
    required int button,
    required bool pressed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_u_16(x, serializer);
          sse_encode_u_16(y, serializer);
          sse_encode_i_32(button, serializer);
          sse_encode_bool(pressed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpRdpMouseConstMeta,
        argValues: [sessionId, x, y, button, pressed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpMouseConstMeta => const TaskConstMeta(
    debugName: "rdp_mouse",
    argNames: ["sessionId", "x", "y", "button", "pressed"],
  );

  @override
  Future<RustRdpFrame> crateApiRdpRdpReadFrame({
    required PlatformInt64 sessionId,
    required PlatformInt64 afterSequence,
    required int waitMillis,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_i_64(afterSequence, serializer);
          sse_encode_u_32(waitMillis, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_rdp_frame,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpRdpReadFrameConstMeta,
        argValues: [sessionId, afterSequence, waitMillis],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpReadFrameConstMeta => const TaskConstMeta(
    debugName: "rdp_read_frame",
    argNames: ["sessionId", "afterSequence", "waitMillis"],
  );

  @override
  Future<RustRdpStatus> crateApiRdpRdpReadStatus({
    required PlatformInt64 sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_rdp_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpRdpReadStatusConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpReadStatusConstMeta => const TaskConstMeta(
    debugName: "rdp_read_status",
    argNames: ["sessionId"],
  );

  @override
  Future<void> crateApiRdpRdpResize({
    required PlatformInt64 sessionId,
    required int width,
    required int height,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_u_16(width, serializer);
          sse_encode_u_16(height, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpRdpResizeConstMeta,
        argValues: [sessionId, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpResizeConstMeta => const TaskConstMeta(
    debugName: "rdp_resize",
    argNames: ["sessionId", "width", "height"],
  );

  @override
  Future<void> crateApiRdpRdpSendScancode({
    required PlatformInt64 sessionId,
    required int scancode,
    required bool pressed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_u_16(scancode, serializer);
          sse_encode_bool(pressed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpRdpSendScancodeConstMeta,
        argValues: [sessionId, scancode, pressed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpSendScancodeConstMeta => const TaskConstMeta(
    debugName: "rdp_send_scancode",
    argNames: ["sessionId", "scancode", "pressed"],
  );

  @override
  Future<void> crateApiRdpRdpSendText({
    required PlatformInt64 sessionId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpRdpSendTextConstMeta,
        argValues: [sessionId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpRdpSendTextConstMeta => const TaskConstMeta(
    debugName: "rdp_send_text",
    argNames: ["sessionId", "text"],
  );

  @override
  Future<void> crateApiCoreSftpChangeDirectory({
    required PlatformInt64 sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSftpChangeDirectoryConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSftpChangeDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "sftp_change_directory",
        argNames: ["sessionId", "path"],
      );

  @override
  Future<void> crateApiCoreSftpClose({required PlatformInt64 sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSftpCloseConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSftpCloseConstMeta =>
      const TaskConstMeta(debugName: "sftp_close", argNames: ["sessionId"]);

  @override
  Future<RustSftpConnectResult> crateApiCoreSftpConnect({
    required RustSftpConnectRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_rust_sftp_connect_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_sftp_connect_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSftpConnectConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSftpConnectConstMeta =>
      const TaskConstMeta(debugName: "sftp_connect", argNames: ["request"]);

  @override
  Future<void> crateApiCoreSftpCreateDirectory({
    required PlatformInt64 sessionId,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSftpCreateDirectoryConstMeta,
        argValues: [sessionId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSftpCreateDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "sftp_create_directory",
        argNames: ["sessionId", "name"],
      );

  @override
  Future<String> crateApiCoreSftpCurrentDirectory({
    required PlatformInt64 sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSftpCurrentDirectoryConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSftpCurrentDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "sftp_current_directory",
        argNames: ["sessionId"],
      );

  @override
  Future<void> crateApiCoreSftpDeleteEmptyDirectory({
    required PlatformInt64 sessionId,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSftpDeleteEmptyDirectoryConstMeta,
        argValues: [sessionId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSftpDeleteEmptyDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "sftp_delete_empty_directory",
        argNames: ["sessionId", "name"],
      );

  @override
  Future<void> crateApiCoreSftpDeleteFile({
    required PlatformInt64 sessionId,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSftpDeleteFileConstMeta,
        argValues: [sessionId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSftpDeleteFileConstMeta => const TaskConstMeta(
    debugName: "sftp_delete_file",
    argNames: ["sessionId", "name"],
  );

  @override
  Future<List<RustSftpEntry>> crateApiCoreSftpListDirectory({
    required PlatformInt64 sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_sftp_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSftpListDirectoryConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSftpListDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "sftp_list_directory",
        argNames: ["sessionId"],
      );

  @override
  Future<void> crateApiCoreSftpRename({
    required PlatformInt64 sessionId,
    required String oldName,
    required String newName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_String(oldName, serializer);
          sse_encode_String(newName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSftpRenameConstMeta,
        argValues: [sessionId, oldName, newName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSftpRenameConstMeta => const TaskConstMeta(
    debugName: "sftp_rename",
    argNames: ["sessionId", "oldName", "newName"],
  );

  @override
  Future<void> crateApiCoreSshClose({required PlatformInt64 sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSshCloseConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSshCloseConstMeta =>
      const TaskConstMeta(debugName: "ssh_close", argNames: ["sessionId"]);

  @override
  Future<RustSshConnectResult> crateApiCoreSshConnect({
    required RustSshConnectRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_rust_ssh_connect_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_ssh_connect_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSshConnectConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSshConnectConstMeta =>
      const TaskConstMeta(debugName: "ssh_connect", argNames: ["request"]);

  @override
  Future<RustSshConnectResult> crateApiCoreSshContinueAuthentication({
    required PlatformInt64 pendingAuthId,
    required List<String> responses,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(pendingAuthId, serializer);
          sse_encode_list_String(responses, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_ssh_connect_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSshContinueAuthenticationConstMeta,
        argValues: [pendingAuthId, responses],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSshContinueAuthenticationConstMeta =>
      const TaskConstMeta(
        debugName: "ssh_continue_authentication",
        argNames: ["pendingAuthId", "responses"],
      );

  @override
  Future<RustSshReadResult> crateApiCoreSshRead({
    required PlatformInt64 sessionId,
    required int maxBytes,
    required int waitMillis,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_u_32(maxBytes, serializer);
          sse_encode_u_32(waitMillis, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_ssh_read_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSshReadConstMeta,
        argValues: [sessionId, maxBytes, waitMillis],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSshReadConstMeta => const TaskConstMeta(
    debugName: "ssh_read",
    argNames: ["sessionId", "maxBytes", "waitMillis"],
  );

  @override
  Future<void> crateApiCoreSshResize({
    required PlatformInt64 sessionId,
    required int width,
    required int height,
    required int pixelWidth,
    required int pixelHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_32(pixelWidth, serializer);
          sse_encode_u_32(pixelHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSshResizeConstMeta,
        argValues: [sessionId, width, height, pixelWidth, pixelHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSshResizeConstMeta => const TaskConstMeta(
    debugName: "ssh_resize",
    argNames: ["sessionId", "width", "height", "pixelWidth", "pixelHeight"],
  );

  @override
  Future<void> crateApiCoreSshWrite({
    required PlatformInt64 sessionId,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreSshWriteConstMeta,
        argValues: [sessionId, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreSshWriteConstMeta => const TaskConstMeta(
    debugName: "ssh_write",
    argNames: ["sessionId", "data"],
  );

  @override
  Future<void> crateApiCoreValidatePrivateKey({
    required String pem,
    String? passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pem, serializer);
          sse_encode_opt_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCoreValidatePrivateKeyConstMeta,
        argValues: [pem, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreValidatePrivateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "validate_private_key",
        argNames: ["pem", "passphrase"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  RustAuthChallenge dco_decode_box_autoadd_rust_auth_challenge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_auth_challenge(raw);
  }

  @protected
  RustHostKey dco_decode_box_autoadd_rust_host_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_host_key(raw);
  }

  @protected
  RustRdpConnectRequest dco_decode_box_autoadd_rust_rdp_connect_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_rdp_connect_request(raw);
  }

  @protected
  RustSftpConnectRequest dco_decode_box_autoadd_rust_sftp_connect_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_sftp_connect_request(raw);
  }

  @protected
  RustSshConnectRequest dco_decode_box_autoadd_rust_ssh_connect_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_ssh_connect_request(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RustInteractivePrompt> dco_decode_list_rust_interactive_prompt(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_rust_interactive_prompt)
        .toList();
  }

  @protected
  List<RustSftpEntry> dco_decode_list_rust_sftp_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_sftp_entry).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  RustAuthChallenge? dco_decode_opt_box_autoadd_rust_auth_challenge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_rust_auth_challenge(raw);
  }

  @protected
  RustHostKey? dco_decode_opt_box_autoadd_rust_host_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_rust_host_key(raw);
  }

  @protected
  RustAuthChallenge dco_decode_rust_auth_challenge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustAuthChallenge(
      name: dco_decode_String(arr[0]),
      instruction: dco_decode_String(arr[1]),
      prompts: dco_decode_list_rust_interactive_prompt(arr[2]),
    );
  }

  @protected
  RustHostKey dco_decode_rust_host_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustHostKey(
      algorithm: dco_decode_String(arr[0]),
      fingerprintSha256: dco_decode_String(arr[1]),
    );
  }

  @protected
  RustInteractivePrompt dco_decode_rust_interactive_prompt(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustInteractivePrompt(
      text: dco_decode_String(arr[0]),
      echo: dco_decode_bool(arr[1]),
    );
  }

  @protected
  RustRdpConnectRequest dco_decode_rust_rdp_connect_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RustRdpConnectRequest(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      username: dco_decode_String(arr[2]),
      password: dco_decode_String(arr[3]),
      domain: dco_decode_String(arr[4]),
      width: dco_decode_u_16(arr[5]),
      height: dco_decode_u_16(arr[6]),
    );
  }

  @protected
  RustRdpConnectResult dco_decode_rust_rdp_connect_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustRdpConnectResult(
      sessionId: dco_decode_i_64(arr[0]),
      renderer: dco_decode_String(arr[1]),
    );
  }

  @protected
  RustRdpFrame dco_decode_rust_rdp_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RustRdpFrame(
      sequence: dco_decode_i_64(arr[0]),
      width: dco_decode_u_16(arr[1]),
      height: dco_decode_u_16(arr[2]),
      rgba: dco_decode_list_prim_u_8_strict(arr[3]),
      state: dco_decode_String(arr[4]),
      errorMessage: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  RustRdpStatus dco_decode_rust_rdp_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RustRdpStatus(
      sequence: dco_decode_i_64(arr[0]),
      width: dco_decode_u_16(arr[1]),
      height: dco_decode_u_16(arr[2]),
      state: dco_decode_String(arr[3]),
      errorMessage: dco_decode_opt_String(arr[4]),
      renderer: dco_decode_String(arr[5]),
      rendererError: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  RustSftpConnectRequest dco_decode_rust_sftp_connect_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RustSftpConnectRequest(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      username: dco_decode_String(arr[2]),
      authKind: dco_decode_String(arr[3]),
      password: dco_decode_String(arr[4]),
      privateKeyPem: dco_decode_String(arr[5]),
      passphrase: dco_decode_opt_String(arr[6]),
      trustedHostKeys: dco_decode_list_String(arr[7]),
    );
  }

  @protected
  RustSftpConnectResult dco_decode_rust_sftp_connect_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RustSftpConnectResult(
      sessionId: dco_decode_opt_box_autoadd_i_64(arr[0]),
      hostKey: dco_decode_opt_box_autoadd_rust_host_key(arr[1]),
      errorCode: dco_decode_opt_String(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  RustSftpEntry dco_decode_rust_sftp_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RustSftpEntry(
      name: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      size: dco_decode_opt_box_autoadd_i_64(arr[2]),
      modifiedSeconds: dco_decode_opt_box_autoadd_i_64(arr[3]),
    );
  }

  @protected
  RustSshConnectRequest dco_decode_rust_ssh_connect_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return RustSshConnectRequest(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      username: dco_decode_String(arr[2]),
      authKind: dco_decode_String(arr[3]),
      password: dco_decode_String(arr[4]),
      privateKeyPem: dco_decode_String(arr[5]),
      passphrase: dco_decode_opt_String(arr[6]),
      trustedHostKeys: dco_decode_list_String(arr[7]),
      terminalWidth: dco_decode_u_32(arr[8]),
      terminalHeight: dco_decode_u_32(arr[9]),
    );
  }

  @protected
  RustSshConnectResult dco_decode_rust_ssh_connect_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RustSshConnectResult(
      sessionId: dco_decode_opt_box_autoadd_i_64(arr[0]),
      pendingAuthId: dco_decode_opt_box_autoadd_i_64(arr[1]),
      hostKey: dco_decode_opt_box_autoadd_rust_host_key(arr[2]),
      challenge: dco_decode_opt_box_autoadd_rust_auth_challenge(arr[3]),
      errorCode: dco_decode_opt_String(arr[4]),
      errorMessage: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  RustSshReadResult dco_decode_rust_ssh_read_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RustSshReadResult(
      stdout: dco_decode_list_prim_u_8_strict(arr[0]),
      stderr: dco_decode_list_prim_u_8_strict(arr[1]),
      closed: dco_decode_bool(arr[2]),
      errorMessage: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  RustAuthChallenge sse_decode_box_autoadd_rust_auth_challenge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_auth_challenge(deserializer));
  }

  @protected
  RustHostKey sse_decode_box_autoadd_rust_host_key(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_host_key(deserializer));
  }

  @protected
  RustRdpConnectRequest sse_decode_box_autoadd_rust_rdp_connect_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_rdp_connect_request(deserializer));
  }

  @protected
  RustSftpConnectRequest sse_decode_box_autoadd_rust_sftp_connect_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_sftp_connect_request(deserializer));
  }

  @protected
  RustSshConnectRequest sse_decode_box_autoadd_rust_ssh_connect_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_ssh_connect_request(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RustInteractivePrompt> sse_decode_list_rust_interactive_prompt(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustInteractivePrompt>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_interactive_prompt(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustSftpEntry> sse_decode_list_rust_sftp_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustSftpEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_sftp_entry(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustAuthChallenge? sse_decode_opt_box_autoadd_rust_auth_challenge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_rust_auth_challenge(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustHostKey? sse_decode_opt_box_autoadd_rust_host_key(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_rust_host_key(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustAuthChallenge sse_decode_rust_auth_challenge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_instruction = sse_decode_String(deserializer);
    var var_prompts = sse_decode_list_rust_interactive_prompt(deserializer);
    return RustAuthChallenge(
      name: var_name,
      instruction: var_instruction,
      prompts: var_prompts,
    );
  }

  @protected
  RustHostKey sse_decode_rust_host_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_algorithm = sse_decode_String(deserializer);
    var var_fingerprintSha256 = sse_decode_String(deserializer);
    return RustHostKey(
      algorithm: var_algorithm,
      fingerprintSha256: var_fingerprintSha256,
    );
  }

  @protected
  RustInteractivePrompt sse_decode_rust_interactive_prompt(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_echo = sse_decode_bool(deserializer);
    return RustInteractivePrompt(text: var_text, echo: var_echo);
  }

  @protected
  RustRdpConnectRequest sse_decode_rust_rdp_connect_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_domain = sse_decode_String(deserializer);
    var var_width = sse_decode_u_16(deserializer);
    var var_height = sse_decode_u_16(deserializer);
    return RustRdpConnectRequest(
      host: var_host,
      port: var_port,
      username: var_username,
      password: var_password,
      domain: var_domain,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  RustRdpConnectResult sse_decode_rust_rdp_connect_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_i_64(deserializer);
    var var_renderer = sse_decode_String(deserializer);
    return RustRdpConnectResult(
      sessionId: var_sessionId,
      renderer: var_renderer,
    );
  }

  @protected
  RustRdpFrame sse_decode_rust_rdp_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sequence = sse_decode_i_64(deserializer);
    var var_width = sse_decode_u_16(deserializer);
    var var_height = sse_decode_u_16(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return RustRdpFrame(
      sequence: var_sequence,
      width: var_width,
      height: var_height,
      rgba: var_rgba,
      state: var_state,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  RustRdpStatus sse_decode_rust_rdp_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sequence = sse_decode_i_64(deserializer);
    var var_width = sse_decode_u_16(deserializer);
    var var_height = sse_decode_u_16(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    var var_renderer = sse_decode_String(deserializer);
    var var_rendererError = sse_decode_opt_String(deserializer);
    return RustRdpStatus(
      sequence: var_sequence,
      width: var_width,
      height: var_height,
      state: var_state,
      errorMessage: var_errorMessage,
      renderer: var_renderer,
      rendererError: var_rendererError,
    );
  }

  @protected
  RustSftpConnectRequest sse_decode_rust_sftp_connect_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_authKind = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_privateKeyPem = sse_decode_String(deserializer);
    var var_passphrase = sse_decode_opt_String(deserializer);
    var var_trustedHostKeys = sse_decode_list_String(deserializer);
    return RustSftpConnectRequest(
      host: var_host,
      port: var_port,
      username: var_username,
      authKind: var_authKind,
      password: var_password,
      privateKeyPem: var_privateKeyPem,
      passphrase: var_passphrase,
      trustedHostKeys: var_trustedHostKeys,
    );
  }

  @protected
  RustSftpConnectResult sse_decode_rust_sftp_connect_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_hostKey = sse_decode_opt_box_autoadd_rust_host_key(deserializer);
    var var_errorCode = sse_decode_opt_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return RustSftpConnectResult(
      sessionId: var_sessionId,
      hostKey: var_hostKey,
      errorCode: var_errorCode,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  RustSftpEntry sse_decode_rust_sftp_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_size = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_modifiedSeconds = sse_decode_opt_box_autoadd_i_64(deserializer);
    return RustSftpEntry(
      name: var_name,
      kind: var_kind,
      size: var_size,
      modifiedSeconds: var_modifiedSeconds,
    );
  }

  @protected
  RustSshConnectRequest sse_decode_rust_ssh_connect_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_authKind = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_privateKeyPem = sse_decode_String(deserializer);
    var var_passphrase = sse_decode_opt_String(deserializer);
    var var_trustedHostKeys = sse_decode_list_String(deserializer);
    var var_terminalWidth = sse_decode_u_32(deserializer);
    var var_terminalHeight = sse_decode_u_32(deserializer);
    return RustSshConnectRequest(
      host: var_host,
      port: var_port,
      username: var_username,
      authKind: var_authKind,
      password: var_password,
      privateKeyPem: var_privateKeyPem,
      passphrase: var_passphrase,
      trustedHostKeys: var_trustedHostKeys,
      terminalWidth: var_terminalWidth,
      terminalHeight: var_terminalHeight,
    );
  }

  @protected
  RustSshConnectResult sse_decode_rust_ssh_connect_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_pendingAuthId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_hostKey = sse_decode_opt_box_autoadd_rust_host_key(deserializer);
    var var_challenge = sse_decode_opt_box_autoadd_rust_auth_challenge(
      deserializer,
    );
    var var_errorCode = sse_decode_opt_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return RustSshConnectResult(
      sessionId: var_sessionId,
      pendingAuthId: var_pendingAuthId,
      hostKey: var_hostKey,
      challenge: var_challenge,
      errorCode: var_errorCode,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  RustSshReadResult sse_decode_rust_ssh_read_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stdout = sse_decode_list_prim_u_8_strict(deserializer);
    var var_stderr = sse_decode_list_prim_u_8_strict(deserializer);
    var var_closed = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return RustSshReadResult(
      stdout: var_stdout,
      stderr: var_stderr,
      closed: var_closed,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_auth_challenge(
    RustAuthChallenge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_auth_challenge(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_host_key(
    RustHostKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_host_key(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_rdp_connect_request(
    RustRdpConnectRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_rdp_connect_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_sftp_connect_request(
    RustSftpConnectRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_sftp_connect_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_ssh_connect_request(
    RustSshConnectRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_ssh_connect_request(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rust_interactive_prompt(
    List<RustInteractivePrompt> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_interactive_prompt(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_sftp_entry(
    List<RustSftpEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_sftp_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_rust_auth_challenge(
    RustAuthChallenge? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_rust_auth_challenge(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_rust_host_key(
    RustHostKey? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_rust_host_key(self, serializer);
    }
  }

  @protected
  void sse_encode_rust_auth_challenge(
    RustAuthChallenge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.instruction, serializer);
    sse_encode_list_rust_interactive_prompt(self.prompts, serializer);
  }

  @protected
  void sse_encode_rust_host_key(RustHostKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.algorithm, serializer);
    sse_encode_String(self.fingerprintSha256, serializer);
  }

  @protected
  void sse_encode_rust_interactive_prompt(
    RustInteractivePrompt self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_bool(self.echo, serializer);
  }

  @protected
  void sse_encode_rust_rdp_connect_request(
    RustRdpConnectRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_String(self.domain, serializer);
    sse_encode_u_16(self.width, serializer);
    sse_encode_u_16(self.height, serializer);
  }

  @protected
  void sse_encode_rust_rdp_connect_result(
    RustRdpConnectResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.sessionId, serializer);
    sse_encode_String(self.renderer, serializer);
  }

  @protected
  void sse_encode_rust_rdp_frame(RustRdpFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.sequence, serializer);
    sse_encode_u_16(self.width, serializer);
    sse_encode_u_16(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_rust_rdp_status(
    RustRdpStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.sequence, serializer);
    sse_encode_u_16(self.width, serializer);
    sse_encode_u_16(self.height, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
    sse_encode_String(self.renderer, serializer);
    sse_encode_opt_String(self.rendererError, serializer);
  }

  @protected
  void sse_encode_rust_sftp_connect_request(
    RustSftpConnectRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.authKind, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_String(self.privateKeyPem, serializer);
    sse_encode_opt_String(self.passphrase, serializer);
    sse_encode_list_String(self.trustedHostKeys, serializer);
  }

  @protected
  void sse_encode_rust_sftp_connect_result(
    RustSftpConnectResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.sessionId, serializer);
    sse_encode_opt_box_autoadd_rust_host_key(self.hostKey, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_rust_sftp_entry(
    RustSftpEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_box_autoadd_i_64(self.size, serializer);
    sse_encode_opt_box_autoadd_i_64(self.modifiedSeconds, serializer);
  }

  @protected
  void sse_encode_rust_ssh_connect_request(
    RustSshConnectRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.authKind, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_String(self.privateKeyPem, serializer);
    sse_encode_opt_String(self.passphrase, serializer);
    sse_encode_list_String(self.trustedHostKeys, serializer);
    sse_encode_u_32(self.terminalWidth, serializer);
    sse_encode_u_32(self.terminalHeight, serializer);
  }

  @protected
  void sse_encode_rust_ssh_connect_result(
    RustSshConnectResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.sessionId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.pendingAuthId, serializer);
    sse_encode_opt_box_autoadd_rust_host_key(self.hostKey, serializer);
    sse_encode_opt_box_autoadd_rust_auth_challenge(self.challenge, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_rust_ssh_read_result(
    RustSshReadResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.stdout, serializer);
    sse_encode_list_prim_u_8_strict(self.stderr, serializer);
    sse_encode_bool(self.closed, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
