// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/core.dart';
import 'api/rdp.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  RustAuthChallenge dco_decode_box_autoadd_rust_auth_challenge(dynamic raw);

  @protected
  RustHostKey dco_decode_box_autoadd_rust_host_key(dynamic raw);

  @protected
  RustRdpConnectRequest dco_decode_box_autoadd_rust_rdp_connect_request(
    dynamic raw,
  );

  @protected
  RustSftpConnectRequest dco_decode_box_autoadd_rust_sftp_connect_request(
    dynamic raw,
  );

  @protected
  RustSshConnectRequest dco_decode_box_autoadd_rust_ssh_connect_request(
    dynamic raw,
  );

  @protected
  RustSshExecRequest dco_decode_box_autoadd_rust_ssh_exec_request(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RustInteractivePrompt> dco_decode_list_rust_interactive_prompt(
    dynamic raw,
  );

  @protected
  List<RustSftpEntry> dco_decode_list_rust_sftp_entry(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  RustAuthChallenge? dco_decode_opt_box_autoadd_rust_auth_challenge(
    dynamic raw,
  );

  @protected
  RustHostKey? dco_decode_opt_box_autoadd_rust_host_key(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  RustAuthChallenge dco_decode_rust_auth_challenge(dynamic raw);

  @protected
  RustHostKey dco_decode_rust_host_key(dynamic raw);

  @protected
  RustInteractivePrompt dco_decode_rust_interactive_prompt(dynamic raw);

  @protected
  RustRdpConnectRequest dco_decode_rust_rdp_connect_request(dynamic raw);

  @protected
  RustRdpConnectResult dco_decode_rust_rdp_connect_result(dynamic raw);

  @protected
  RustRdpFrame dco_decode_rust_rdp_frame(dynamic raw);

  @protected
  RustRdpStatus dco_decode_rust_rdp_status(dynamic raw);

  @protected
  RustSftpConnectRequest dco_decode_rust_sftp_connect_request(dynamic raw);

  @protected
  RustSftpConnectResult dco_decode_rust_sftp_connect_result(dynamic raw);

  @protected
  RustSftpEntry dco_decode_rust_sftp_entry(dynamic raw);

  @protected
  RustSshConnectRequest dco_decode_rust_ssh_connect_request(dynamic raw);

  @protected
  RustSshConnectResult dco_decode_rust_ssh_connect_result(dynamic raw);

  @protected
  RustSshExecRequest dco_decode_rust_ssh_exec_request(dynamic raw);

  @protected
  RustSshExecResult dco_decode_rust_ssh_exec_result(dynamic raw);

  @protected
  RustSshReadResult dco_decode_rust_ssh_read_result(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RustAuthChallenge sse_decode_box_autoadd_rust_auth_challenge(
    SseDeserializer deserializer,
  );

  @protected
  RustHostKey sse_decode_box_autoadd_rust_host_key(
    SseDeserializer deserializer,
  );

  @protected
  RustRdpConnectRequest sse_decode_box_autoadd_rust_rdp_connect_request(
    SseDeserializer deserializer,
  );

  @protected
  RustSftpConnectRequest sse_decode_box_autoadd_rust_sftp_connect_request(
    SseDeserializer deserializer,
  );

  @protected
  RustSshConnectRequest sse_decode_box_autoadd_rust_ssh_connect_request(
    SseDeserializer deserializer,
  );

  @protected
  RustSshExecRequest sse_decode_box_autoadd_rust_ssh_exec_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RustInteractivePrompt> sse_decode_list_rust_interactive_prompt(
    SseDeserializer deserializer,
  );

  @protected
  List<RustSftpEntry> sse_decode_list_rust_sftp_entry(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RustAuthChallenge? sse_decode_opt_box_autoadd_rust_auth_challenge(
    SseDeserializer deserializer,
  );

  @protected
  RustHostKey? sse_decode_opt_box_autoadd_rust_host_key(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  RustAuthChallenge sse_decode_rust_auth_challenge(
    SseDeserializer deserializer,
  );

  @protected
  RustHostKey sse_decode_rust_host_key(SseDeserializer deserializer);

  @protected
  RustInteractivePrompt sse_decode_rust_interactive_prompt(
    SseDeserializer deserializer,
  );

  @protected
  RustRdpConnectRequest sse_decode_rust_rdp_connect_request(
    SseDeserializer deserializer,
  );

  @protected
  RustRdpConnectResult sse_decode_rust_rdp_connect_result(
    SseDeserializer deserializer,
  );

  @protected
  RustRdpFrame sse_decode_rust_rdp_frame(SseDeserializer deserializer);

  @protected
  RustRdpStatus sse_decode_rust_rdp_status(SseDeserializer deserializer);

  @protected
  RustSftpConnectRequest sse_decode_rust_sftp_connect_request(
    SseDeserializer deserializer,
  );

  @protected
  RustSftpConnectResult sse_decode_rust_sftp_connect_result(
    SseDeserializer deserializer,
  );

  @protected
  RustSftpEntry sse_decode_rust_sftp_entry(SseDeserializer deserializer);

  @protected
  RustSshConnectRequest sse_decode_rust_ssh_connect_request(
    SseDeserializer deserializer,
  );

  @protected
  RustSshConnectResult sse_decode_rust_ssh_connect_result(
    SseDeserializer deserializer,
  );

  @protected
  RustSshExecRequest sse_decode_rust_ssh_exec_request(
    SseDeserializer deserializer,
  );

  @protected
  RustSshExecResult sse_decode_rust_ssh_exec_result(
    SseDeserializer deserializer,
  );

  @protected
  RustSshReadResult sse_decode_rust_ssh_read_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_auth_challenge(
    RustAuthChallenge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_host_key(
    RustHostKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_rdp_connect_request(
    RustRdpConnectRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_sftp_connect_request(
    RustSftpConnectRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_ssh_connect_request(
    RustSshConnectRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rust_ssh_exec_request(
    RustSshExecRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_interactive_prompt(
    List<RustInteractivePrompt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rust_sftp_entry(
    List<RustSftpEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rust_auth_challenge(
    RustAuthChallenge? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rust_host_key(
    RustHostKey? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_rust_auth_challenge(
    RustAuthChallenge self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_host_key(RustHostKey self, SseSerializer serializer);

  @protected
  void sse_encode_rust_interactive_prompt(
    RustInteractivePrompt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_rdp_connect_request(
    RustRdpConnectRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_rdp_connect_result(
    RustRdpConnectResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_rdp_frame(RustRdpFrame self, SseSerializer serializer);

  @protected
  void sse_encode_rust_rdp_status(RustRdpStatus self, SseSerializer serializer);

  @protected
  void sse_encode_rust_sftp_connect_request(
    RustSftpConnectRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_sftp_connect_result(
    RustSftpConnectResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_sftp_entry(RustSftpEntry self, SseSerializer serializer);

  @protected
  void sse_encode_rust_ssh_connect_request(
    RustSshConnectRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_ssh_connect_result(
    RustSshConnectResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_ssh_exec_request(
    RustSshExecRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_ssh_exec_result(
    RustSshExecResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rust_ssh_read_result(
    RustSshReadResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
