// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_limited`, `append_output`, `authenticate_private_key`, `authenticate_sftp`, `authenticate`, `connect_client`, `connect_error`, `drain_queue`, `execute_ssh_command`, `finalize_ssh_session`, `get_sftp_session`, `get_ssh_session`, `host_key_identity`, `len`, `next_id`, `release_excess_capacity`, `resolve_sftp_path`, `sftp_connect_error`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AuthenticationOutcome`, `HostKeyHandler`, `OutputBuffer`, `PendingAuthentication`, `SftpSessionState`, `SshSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `check_server_key`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

Future<RustSshConnectResult> sshConnect({
  required RustSshConnectRequest request,
}) => RustLib.instance.api.crateApiCoreSshConnect(request: request);

Future<RustSshConnectResult> sshContinueAuthentication({
  required PlatformInt64 pendingAuthId,
  required List<String> responses,
}) => RustLib.instance.api.crateApiCoreSshContinueAuthentication(
  pendingAuthId: pendingAuthId,
  responses: responses,
);

Future<RustSshReadResult> sshRead({
  required PlatformInt64 sessionId,
  required int maxBytes,
  required int waitMillis,
}) => RustLib.instance.api.crateApiCoreSshRead(
  sessionId: sessionId,
  maxBytes: maxBytes,
  waitMillis: waitMillis,
);

Future<void> sshWrite({
  required PlatformInt64 sessionId,
  required List<int> data,
}) =>
    RustLib.instance.api.crateApiCoreSshWrite(sessionId: sessionId, data: data);

Future<void> sshResize({
  required PlatformInt64 sessionId,
  required int width,
  required int height,
  required int pixelWidth,
  required int pixelHeight,
}) => RustLib.instance.api.crateApiCoreSshResize(
  sessionId: sessionId,
  width: width,
  height: height,
  pixelWidth: pixelWidth,
  pixelHeight: pixelHeight,
);

Future<void> sshClose({required PlatformInt64 sessionId}) =>
    RustLib.instance.api.crateApiCoreSshClose(sessionId: sessionId);

Future<RustSshExecResult> sshExecute({required RustSshExecRequest request}) =>
    RustLib.instance.api.crateApiCoreSshExecute(request: request);

Future<void> sshCancelExecution({required PlatformInt64 executionId}) => RustLib
    .instance
    .api
    .crateApiCoreSshCancelExecution(executionId: executionId);

Future<bool> privateKeyIsEncrypted({required String pem}) =>
    RustLib.instance.api.crateApiCorePrivateKeyIsEncrypted(pem: pem);

Future<void> validatePrivateKey({required String pem, String? passphrase}) =>
    RustLib.instance.api.crateApiCoreValidatePrivateKey(
      pem: pem,
      passphrase: passphrase,
    );

Future<RustSftpConnectResult> sftpConnect({
  required RustSftpConnectRequest request,
}) => RustLib.instance.api.crateApiCoreSftpConnect(request: request);

Future<String> sftpCurrentDirectory({required PlatformInt64 sessionId}) =>
    RustLib.instance.api.crateApiCoreSftpCurrentDirectory(sessionId: sessionId);

Future<List<RustSftpEntry>> sftpListDirectory({
  required PlatformInt64 sessionId,
}) => RustLib.instance.api.crateApiCoreSftpListDirectory(sessionId: sessionId);

Future<void> sftpChangeDirectory({
  required PlatformInt64 sessionId,
  required String path,
}) => RustLib.instance.api.crateApiCoreSftpChangeDirectory(
  sessionId: sessionId,
  path: path,
);

Future<void> sftpCreateDirectory({
  required PlatformInt64 sessionId,
  required String name,
}) => RustLib.instance.api.crateApiCoreSftpCreateDirectory(
  sessionId: sessionId,
  name: name,
);

Future<void> sftpRename({
  required PlatformInt64 sessionId,
  required String oldName,
  required String newName,
}) => RustLib.instance.api.crateApiCoreSftpRename(
  sessionId: sessionId,
  oldName: oldName,
  newName: newName,
);

Future<void> sftpDeleteFile({
  required PlatformInt64 sessionId,
  required String name,
}) => RustLib.instance.api.crateApiCoreSftpDeleteFile(
  sessionId: sessionId,
  name: name,
);

Future<void> sftpDeleteEmptyDirectory({
  required PlatformInt64 sessionId,
  required String name,
}) => RustLib.instance.api.crateApiCoreSftpDeleteEmptyDirectory(
  sessionId: sessionId,
  name: name,
);

Future<void> sftpClose({required PlatformInt64 sessionId}) =>
    RustLib.instance.api.crateApiCoreSftpClose(sessionId: sessionId);

class RustAuthChallenge {
  final String name;
  final String instruction;
  final List<RustInteractivePrompt> prompts;

  const RustAuthChallenge({
    required this.name,
    required this.instruction,
    required this.prompts,
  });

  @override
  int get hashCode => name.hashCode ^ instruction.hashCode ^ prompts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustAuthChallenge &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          instruction == other.instruction &&
          prompts == other.prompts;
}

class RustHostKey {
  final String algorithm;
  final String fingerprintSha256;

  const RustHostKey({required this.algorithm, required this.fingerprintSha256});

  @override
  int get hashCode => algorithm.hashCode ^ fingerprintSha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustHostKey &&
          runtimeType == other.runtimeType &&
          algorithm == other.algorithm &&
          fingerprintSha256 == other.fingerprintSha256;
}

class RustInteractivePrompt {
  final String text;
  final bool echo;

  const RustInteractivePrompt({required this.text, required this.echo});

  @override
  int get hashCode => text.hashCode ^ echo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustInteractivePrompt &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          echo == other.echo;
}

class RustSftpConnectRequest {
  final String host;
  final int port;
  final String username;
  final String authKind;
  final String password;
  final String privateKeyPem;
  final String? passphrase;
  final List<String> trustedHostKeys;

  const RustSftpConnectRequest({
    required this.host,
    required this.port,
    required this.username,
    required this.authKind,
    required this.password,
    required this.privateKeyPem,
    this.passphrase,
    required this.trustedHostKeys,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      authKind.hashCode ^
      password.hashCode ^
      privateKeyPem.hashCode ^
      passphrase.hashCode ^
      trustedHostKeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSftpConnectRequest &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          authKind == other.authKind &&
          password == other.password &&
          privateKeyPem == other.privateKeyPem &&
          passphrase == other.passphrase &&
          trustedHostKeys == other.trustedHostKeys;
}

class RustSftpConnectResult {
  final PlatformInt64? sessionId;
  final RustHostKey? hostKey;
  final String? errorCode;
  final String? errorMessage;

  const RustSftpConnectResult({
    this.sessionId,
    this.hostKey,
    this.errorCode,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      hostKey.hashCode ^
      errorCode.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSftpConnectResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          hostKey == other.hostKey &&
          errorCode == other.errorCode &&
          errorMessage == other.errorMessage;
}

class RustSftpEntry {
  final String name;
  final String kind;
  final PlatformInt64? size;
  final PlatformInt64? modifiedSeconds;

  const RustSftpEntry({
    required this.name,
    required this.kind,
    this.size,
    this.modifiedSeconds,
  });

  @override
  int get hashCode =>
      name.hashCode ^ kind.hashCode ^ size.hashCode ^ modifiedSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSftpEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          kind == other.kind &&
          size == other.size &&
          modifiedSeconds == other.modifiedSeconds;
}

class RustSshConnectRequest {
  final String host;
  final int port;
  final String username;
  final String authKind;
  final String password;
  final String privateKeyPem;
  final String? passphrase;
  final List<String> trustedHostKeys;
  final int terminalWidth;
  final int terminalHeight;

  const RustSshConnectRequest({
    required this.host,
    required this.port,
    required this.username,
    required this.authKind,
    required this.password,
    required this.privateKeyPem,
    this.passphrase,
    required this.trustedHostKeys,
    required this.terminalWidth,
    required this.terminalHeight,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      authKind.hashCode ^
      password.hashCode ^
      privateKeyPem.hashCode ^
      passphrase.hashCode ^
      trustedHostKeys.hashCode ^
      terminalWidth.hashCode ^
      terminalHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSshConnectRequest &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          authKind == other.authKind &&
          password == other.password &&
          privateKeyPem == other.privateKeyPem &&
          passphrase == other.passphrase &&
          trustedHostKeys == other.trustedHostKeys &&
          terminalWidth == other.terminalWidth &&
          terminalHeight == other.terminalHeight;
}

class RustSshConnectResult {
  final PlatformInt64? sessionId;
  final PlatformInt64? pendingAuthId;
  final RustHostKey? hostKey;
  final RustAuthChallenge? challenge;
  final String? errorCode;
  final String? errorMessage;

  const RustSshConnectResult({
    this.sessionId,
    this.pendingAuthId,
    this.hostKey,
    this.challenge,
    this.errorCode,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      pendingAuthId.hashCode ^
      hostKey.hashCode ^
      challenge.hashCode ^
      errorCode.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSshConnectResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          pendingAuthId == other.pendingAuthId &&
          hostKey == other.hostKey &&
          challenge == other.challenge &&
          errorCode == other.errorCode &&
          errorMessage == other.errorMessage;
}

class RustSshExecRequest {
  final PlatformInt64 executionId;
  final String host;
  final int port;
  final String username;
  final String authKind;
  final String password;
  final String privateKeyPem;
  final String? passphrase;
  final List<String> trustedHostKeys;
  final String command;
  final int timeoutMillis;
  final int outputLimitBytes;

  const RustSshExecRequest({
    required this.executionId,
    required this.host,
    required this.port,
    required this.username,
    required this.authKind,
    required this.password,
    required this.privateKeyPem,
    this.passphrase,
    required this.trustedHostKeys,
    required this.command,
    required this.timeoutMillis,
    required this.outputLimitBytes,
  });

  @override
  int get hashCode =>
      executionId.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      authKind.hashCode ^
      password.hashCode ^
      privateKeyPem.hashCode ^
      passphrase.hashCode ^
      trustedHostKeys.hashCode ^
      command.hashCode ^
      timeoutMillis.hashCode ^
      outputLimitBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSshExecRequest &&
          runtimeType == other.runtimeType &&
          executionId == other.executionId &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          authKind == other.authKind &&
          password == other.password &&
          privateKeyPem == other.privateKeyPem &&
          passphrase == other.passphrase &&
          trustedHostKeys == other.trustedHostKeys &&
          command == other.command &&
          timeoutMillis == other.timeoutMillis &&
          outputLimitBytes == other.outputLimitBytes;
}

class RustSshExecResult {
  final Uint8List stdout;
  final Uint8List stderr;
  final int? exitStatus;
  final bool timedOut;
  final bool cancelled;
  final bool truncated;
  final String? errorCode;
  final String? errorMessage;

  const RustSshExecResult({
    required this.stdout,
    required this.stderr,
    this.exitStatus,
    required this.timedOut,
    required this.cancelled,
    required this.truncated,
    this.errorCode,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      stdout.hashCode ^
      stderr.hashCode ^
      exitStatus.hashCode ^
      timedOut.hashCode ^
      cancelled.hashCode ^
      truncated.hashCode ^
      errorCode.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSshExecResult &&
          runtimeType == other.runtimeType &&
          stdout == other.stdout &&
          stderr == other.stderr &&
          exitStatus == other.exitStatus &&
          timedOut == other.timedOut &&
          cancelled == other.cancelled &&
          truncated == other.truncated &&
          errorCode == other.errorCode &&
          errorMessage == other.errorMessage;
}

class RustSshReadResult {
  final Uint8List stdout;
  final Uint8List stderr;
  final bool closed;
  final String? errorMessage;

  const RustSshReadResult({
    required this.stdout,
    required this.stderr,
    required this.closed,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      stdout.hashCode ^
      stderr.hashCode ^
      closed.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSshReadResult &&
          runtimeType == other.runtimeType &&
          stdout == other.stdout &&
          stderr == other.stderr &&
          closed == other.closed &&
          errorMessage == other.errorMessage;
}
