// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_output_event`, `copy_frame_after`, `get_session`, `renderer_error`, `send_mouse_event`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RdpFrameData`, `RdpSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<RustRdpConnectResult> rdpConnect({
  required RustRdpConnectRequest request,
}) => RustLib.instance.api.crateApiRdpRdpConnect(request: request);

Future<RustRdpStatus> rdpReadStatus({required PlatformInt64 sessionId}) =>
    RustLib.instance.api.crateApiRdpRdpReadStatus(sessionId: sessionId);

Future<RustRdpFrame> rdpReadFrame({
  required PlatformInt64 sessionId,
  required PlatformInt64 afterSequence,
  required int waitMillis,
}) => RustLib.instance.api.crateApiRdpRdpReadFrame(
  sessionId: sessionId,
  afterSequence: afterSequence,
  waitMillis: waitMillis,
);

Future<void> rdpResize({
  required PlatformInt64 sessionId,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiRdpRdpResize(
  sessionId: sessionId,
  width: width,
  height: height,
);

Future<void> rdpMouse({
  required PlatformInt64 sessionId,
  required int x,
  required int y,
  required int button,
  required bool pressed,
}) => RustLib.instance.api.crateApiRdpRdpMouse(
  sessionId: sessionId,
  x: x,
  y: y,
  button: button,
  pressed: pressed,
);

Future<void> rdpSendText({
  required PlatformInt64 sessionId,
  required String text,
}) => RustLib.instance.api.crateApiRdpRdpSendText(
  sessionId: sessionId,
  text: text,
);

Future<void> rdpSendScancode({
  required PlatformInt64 sessionId,
  required int scancode,
  required bool pressed,
}) => RustLib.instance.api.crateApiRdpRdpSendScancode(
  sessionId: sessionId,
  scancode: scancode,
  pressed: pressed,
);

Future<void> rdpClose({required PlatformInt64 sessionId}) =>
    RustLib.instance.api.crateApiRdpRdpClose(sessionId: sessionId);

class RustRdpConnectRequest {
  final String host;
  final int port;
  final String username;
  final String password;
  final String domain;
  final int width;
  final int height;

  const RustRdpConnectRequest({
    required this.host,
    required this.port,
    required this.username,
    required this.password,
    required this.domain,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      domain.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRdpConnectRequest &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          domain == other.domain &&
          width == other.width &&
          height == other.height;
}

class RustRdpConnectResult {
  final PlatformInt64 sessionId;
  final String renderer;

  const RustRdpConnectResult({required this.sessionId, required this.renderer});

  @override
  int get hashCode => sessionId.hashCode ^ renderer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRdpConnectResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          renderer == other.renderer;
}

class RustRdpFrame {
  final PlatformInt64 sequence;
  final int width;
  final int height;
  final Uint8List rgba;
  final String state;
  final String? errorMessage;

  const RustRdpFrame({
    required this.sequence,
    required this.width,
    required this.height,
    required this.rgba,
    required this.state,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      sequence.hashCode ^
      width.hashCode ^
      height.hashCode ^
      rgba.hashCode ^
      state.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRdpFrame &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba &&
          state == other.state &&
          errorMessage == other.errorMessage;
}

class RustRdpStatus {
  final PlatformInt64 sequence;
  final int width;
  final int height;
  final String state;
  final String? errorMessage;
  final String renderer;
  final String? rendererError;

  const RustRdpStatus({
    required this.sequence,
    required this.width,
    required this.height,
    required this.state,
    this.errorMessage,
    required this.renderer,
    this.rendererError,
  });

  @override
  int get hashCode =>
      sequence.hashCode ^
      width.hashCode ^
      height.hashCode ^
      state.hashCode ^
      errorMessage.hashCode ^
      renderer.hashCode ^
      rendererError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRdpStatus &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          width == other.width &&
          height == other.height &&
          state == other.state &&
          errorMessage == other.errorMessage &&
          renderer == other.renderer &&
          rendererError == other.rendererError;
}
